name: "Update bundled_gems"

on:
  schedule:
    - cron: '15 7 * * *'

jobs:
  Update-bundled_gems:

    runs-on: ubuntu-latest

    steps:
    - name: Install libraries
      run: |
        set -x
        sudo apt-get update -q || :
        sudo apt-get install --no-install-recommends -q -y git ruby
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Checkout ruby/ruby
      run: git clone --single-branch --depth=1 https://github.com/ruby/ruby ruby
      shell: bash

    - name: Update
      run: |
        ruby -rrubygems tool/update-bundled_gems.rb gems/bundled_gems |
        tool/ifchange gems/bundled_gems -
        git diff --no-ext-diff --ignore-submodules --exit-code
      working-directory: ruby

    - uses: ruby/action-slack@54175162371f1f7c8eb94d7c8644ee2479fcd375 # v3.2.2
      with:
        payload: |
          {
            "attachments": [{
              "text": "${{ job.status }}: bundled_gems <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>, see also <https://github.com/ruby/ruby/actions/workflows/bundled_gems.yml|bundled_gems in ruby/ruby>",
              "color": "danger"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
      if: failure()
