name: Remove pub/tmp/ruby-*

on:
  repository_dispatch:
    types:
      - "Remove pub/tmp/ruby-*"
  workflow_dispatch:
    inputs:
      TARGET_VERSION:
        description: The version of Ruby to remove tmp archives in https://ftp.ruby-lang.org/pub/tmp/
        required: true
        default: 3.0.0-preview1-draft

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove from s3
        run: |
          set -x
          TARGET_VERSION="${{ github.event.inputs.TARGET_VERSION }}""${GITHUB_EVENT_ACTION#Remove pub/tmp/ruby-}"
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 rm "s3://ftp.r-l.o/pub/tmp/ruby-${TARGET_VERSION}$ext"
            curl -sS -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/tmp/ruby-${TARGET_VERSION}$ext"
          done
          aws s3 rm "s3://ftp.r-l.o/pub/tmp/ruby-info-${TARGET_VERSION}.yml"
          curl -sS -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/tmp/ruby-info-${TARGET_VERSION}.yml"
          curl -sS -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/tmp/"
        env:
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                title: "${{ github.event.action }} ${{ github.ref }}",
                title_link: "https://cache.ruby-lang.org/pub/tmp/",
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
        if: failure()
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                title: "${{ github.event.action }} ${{ github.ref }}",
                title_link: "https://cache.ruby-lang.org/pub/tmp/",
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>",
                "color": "good"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
        if: success()
